server:
  port: 8080
  context-path: /xxl-job-admin
management:
  context-path: /actuator
  health:
    mail:
      enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xxl_job_212?Unicode=true&characterEncoding=UTF-8
    tomcat:
      max-wait: 1000
      max-active: 30
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
xxl:
  job:
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
    accessToken:
    i18n:

